;;;; Recognizer.lisp
;;;; Recursive descent parser for validating token sequences

(load "Common.lisp")

;;; Global parser state
(defvar *tokens* nil)           ; List of all lex structures
(defvar *current-index* 0)      ; Index of current token being examined
(defvar *output-stream* nil)    ; Output file stream for error messages

;;; Main recognizer function
(defun recognize-file (input-file output-file)
  "Parse tokens from input file and validate against grammar"
  (setf *tokens* (read-tokens-from-file input-file))
  (setf *current-index* 0)
  
  (with-open-file (stream output-file
                          :direction :output
                          :if-exists :supersede
                          :if-does-not-exist :create)
    (setf *output-stream* stream)
    
    ;; Parse starting from top-level grammar rule
    (parse-function)
    
    ;; Check that all tokens were consumed
    (when (< *current-index* (length *tokens*))
      (report-error (format nil "Only consumed ~D of the ~D given tokens"
                           *current-index*
                           (length *tokens*))))
    
    ;; If we get here, parsing succeeded
    (format stream "PARSED!!!~%")))

;;; Read tokens from file generated by Tokenizer
(defun read-tokens-from-file (filepath)
  "Read token and lexeme pairs from file into list of lex structures"
  (with-open-file (stream filepath :direction :input)
    (loop for line = (read-line stream nil)
          while line
          collect (parse-token-line line))))

;;; Parse a single line of token output (format: "TOKEN_TYPE lexeme")
(defun parse-token-line (line)
  "Parse a line like 'VARTYPE int' into a lex structure"
  (let* ((space-pos (position #\Space line))
         (token-str (subseq line 0 space-pos))
         (lexeme (subseq line (1+ space-pos))))
    (make-lex :token (intern (substitute #\- #\_ token-str) :keyword)
              :lexeme lexeme)))

;;; Report error and exit
(defun report-error (message)
  "Write error message to output file and exit"
  (format *output-stream* "Error: ~A~%" message)
  (force-output *output-stream*)  ; Ensure output is written before exit
  (close *output-stream*)          ; Close the stream explicitly
  (sb-ext:exit :code 0))

;;; Get current token without consuming it (lookahead)
(defun peek-token ()
  "Return current token type without advancing, or NIL if at end"
  (if (< *current-index* (length *tokens*))
      (lex-token (nth *current-index* *tokens*))
      nil))

;;; Get current token number (1-indexed for error messages)
(defun current-token-number ()
  "Return current token number (1-indexed)"
  (1+ *current-index*))

;;; Consume current token if it matches expected type
(defun match-token (expected-token rule-name)
  "Consume token if it matches expected type, otherwise report error"
  (let ((actual-token (peek-token)))
    (if (eq actual-token expected-token)
        (progn
          (incf *current-index*)
          t)
        (report-error 
         (format nil "In grammar rule ~A, expected token #~D to be ~A but was ~A"
                 rule-name
                 (current-token-number)
                 (token-to-string expected-token)
                 (if actual-token 
                     (token-to-string actual-token)
                     "EOF"))))))

;;; Check if current token matches any in a list
(defun token-in-list-p (token-list)
  "Return T if current token is in the given list"
  (member (peek-token) token-list))

;;; Grammar rule: function --> header body
(defun parse-function ()
  "Parse a function declaration"
  (parse-header)
  (parse-body))

;;; Grammar rule: header --> VARTYPE IDENTIFIER LEFT_PARENTHESIS [arg-decl] RIGHT_PARENTHESIS
(defun parse-header ()
  "Parse function header"
  (match-token :VARTYPE "header")
  (match-token :IDENTIFIER "header")
  (match-token :LEFT-PARENTHESIS "header")
  
  ;; Optional arg-decl (starts with VARTYPE)
  (when (eq (peek-token) :VARTYPE)
    (parse-arg-decl))
  
  (match-token :RIGHT-PARENTHESIS "header"))

;;; Grammar rule: arg-decl --> VARTYPE IDENTIFIER {COMMA VARTYPE IDENTIFIER}
(defun parse-arg-decl ()
  "Parse argument declaration list"
  (match-token :VARTYPE "arg-decl")
  (match-token :IDENTIFIER "arg-decl")
  
  ;; Zero or more additional arguments
  (loop while (eq (peek-token) :COMMA) do
    (match-token :COMMA "arg-decl")
    (match-token :VARTYPE "arg-decl")
    (match-token :IDENTIFIER "arg-decl")))

;;; Grammar rule: body --> LEFT_BRACKET [statement-list] RIGHT_BRACKET
(defun parse-body ()
  "Parse function body"
  (match-token :LEFT-BRACKET "body")
  
  ;; Optional statement-list (starts with WHILE, RETURN, or IDENTIFIER)
  (when (token-in-list-p '(:WHILE-KEYWORD :RETURN-KEYWORD :IDENTIFIER))
    (parse-statement-list))
  
  (match-token :RIGHT-BRACKET "body"))

;;; Grammar rule: statement-list --> statement {statement}
(defun parse-statement-list ()
  "Parse list of statements"
  (parse-statement)
  
  ;; Zero or more additional statements
  (loop while (token-in-list-p '(:WHILE-KEYWORD :RETURN-KEYWORD :IDENTIFIER)) do
    (parse-statement)))

;;; Grammar rule: statement --> while-loop | return | assignment
(defun parse-statement ()
  "Parse a single statement"
  (cond
    ((eq (peek-token) :WHILE-KEYWORD)
     (parse-while-loop))
    
    ((eq (peek-token) :RETURN-KEYWORD)
     (parse-return))
    
    ((eq (peek-token) :IDENTIFIER)
     (parse-assignment))
    
    (t
     (report-error "In grammar rule statement, expected a valid statement to be present but was not."))))

;;; Grammar rule: while-loop --> WHILE_KEYWORD LEFT_PARENTHESIS expression RIGHT_PARENTHESIS body
(defun parse-while-loop ()
  "Parse while loop"
  (match-token :WHILE-KEYWORD "while-loop")
  (match-token :LEFT-PARENTHESIS "while-loop")
  (parse-expression)
  (match-token :RIGHT-PARENTHESIS "while-loop")
  (parse-body))

;;; Grammar rule: return --> RETURN_KEYWORD expression EOL
(defun parse-return ()
  "Parse return statement"
  (match-token :RETURN-KEYWORD "return")
  (parse-expression)
  (match-token :EOL "return"))

;;; Grammar rule: assignment --> IDENTIFIER EQUAL expression EOL
(defun parse-assignment ()
  "Parse assignment statement"
  (match-token :IDENTIFIER "assignment")
  (match-token :EQUAL "assignment")
  (parse-expression)
  (match-token :EOL "assignment"))

;;; Grammar rule: expression --> term {BINOP term} | LEFT_PARENTHESIS expression RIGHT_PARENTHESIS
;;; Note: The grammar allows for parenthesized expressions OR term sequences with BINOP
;;; A parenthesized expression is a complete expression unit
(defun parse-expression ()
  "Parse expression"
  (cond
    ;; Parenthesized expression
    ((eq (peek-token) :LEFT-PARENTHESIS)
     (match-token :LEFT-PARENTHESIS "expression")
     (parse-expression)
     (match-token :RIGHT-PARENTHESIS "expression")
     ;; After a parenthesized expression, check for BINOP term continuations
     (loop while (eq (peek-token) :BINOP) do
       (match-token :BINOP "expression")
       ;; The next part can be another term or parenthesized expression
       (if (eq (peek-token) :LEFT-PARENTHESIS)
           (progn
             (match-token :LEFT-PARENTHESIS "expression")
             (parse-expression)
             (match-token :RIGHT-PARENTHESIS "expression"))
           (parse-term))))
    
    ;; Term-based expression
    ((token-in-list-p '(:IDENTIFIER :NUMBER))
     (parse-term)
     ;; Zero or more BINOP term pairs
     (loop while (eq (peek-token) :BINOP) do
       (match-token :BINOP "expression")
       ;; The next part can be a term or parenthesized expression
       (if (eq (peek-token) :LEFT-PARENTHESIS)
           (progn
             (match-token :LEFT-PARENTHESIS "expression")
             (parse-expression)
             (match-token :RIGHT-PARENTHESIS "expression"))
           (parse-term))))
    
    (t
     (report-error "In grammar rule expression, expected a valid expression to be present but was not."))))

;;; Grammar rule: term --> IDENTIFIER | NUMBER
(defun parse-term ()
  "Parse term"
  (cond
    ((eq (peek-token) :IDENTIFIER)
     (match-token :IDENTIFIER "term"))
    
    ((eq (peek-token) :NUMBER)
     (match-token :NUMBER "term"))
    
    (t
     (report-error "In grammar rule term, expected a valid term to be present but was not."))))

;;; Entry point - parse command line arguments and run recognizer
(defun main ()
  "Main entry point for recognizer program"
  (let ((args sb-ext:*posix-argv*))  ; For SBCL
    (when (< (length args) 3)
      (format *error-output* "Usage: ~A <input-file> <output-file>~%" (first args))
      (sb-ext:exit :code 1))
    
    (let ((input-file (second args))
          (output-file (third args)))
      (recognize-file input-file output-file))))

;;; Run main function
(main)
